//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Request
    {
        public int id { get; set; }
        public string RequestNo { get; set; }
        public int ProductID { get; set; }
        public int CusID { get; set; }
        public Nullable<int> PlanID { get; set; }
        public string RequestDemoDay { get; set; }
        public Nullable<int> DealID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual Deal Deal { get; set; }
        public virtual productMarketPlan productMarketPlan { get; set; }
        public virtual softwareProduct softwareProduct { get; set; }
    }
}
