//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_Item
    {
        public int id { get; set; }
        public int dealID { get; set; }
        public int planID { get; set; }
        public double price { get; set; }
        public int Quantity { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual productMarketPlan productMarketPlan { get; set; }
    }
}
