//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Template
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string MailContent { get; set; }
        public string creatorID { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> CateID { get; set; }
    
        public virtual EMAIL_Category EMAIL_Category { get; set; }
    }
}
