//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerNotification
    {
        public int id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string NotiContent { get; set; }
        public bool viewed { get; set; }
        public Nullable<int> dealID { get; set; }
        public Nullable<int> requestID { get; set; }
    
        public virtual Customer_Request Customer_Request { get; set; }
        public virtual Deal Deal { get; set; }
    }
}
