//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int CustomerID { get; set; }
        public int Amount { get; set; }
        public int PaymentTypeID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual order order { get; set; }
        public virtual payment_status payment_status { get; set; }
    }
}
