//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleRepCommision
    {
        public int id { get; set; }
        public string SaleRepID { get; set; }
        public System.DateTime DateIssue { get; set; }
        public double Total { get; set; }
        public Nullable<double> Paid { get; set; }
        public string Note { get; set; }
        public Nullable<double> MoneyFromSubcription { get; set; }
        public Nullable<double> MoneyFromNewContract { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
