//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketComments = new HashSet<TicketComment>();
            this.TicketFiles = new HashSet<TicketFile>();
        }
    
        public int id { get; set; }
        public string TicketName { get; set; }
        public int TicketCategory { get; set; }
        public int TicketServerity { get; set; }
        public int TicketStatus { get; set; }
        public string Creator { get; set; }
        public string Description { get; set; }
        public string ScreenShots { get; set; }
        public string AsignedTo { get; set; }
        public int ViewCounted { get; set; }
        public System.DateTime CreatedDay { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual TicketCategory TicketCategory1 { get; set; }
        public virtual TicketServerity TicketServerity1 { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketComment> TicketComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketFile> TicketFiles { get; set; }
    }
}
