//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oder_item
    {
        public int id { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> licenseID { get; set; }
    
        public virtual License License { get; set; }
        public virtual order order { get; set; }
    }
}
