//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.company_responsible = new HashSet<company_responsible>();
            this.contacts = new HashSet<contact>();
        }
    
        public int id { get; set; }
        public string companyName { get; set; }
        public string logo { get; set; }
        public string Industry { get; set; }
        public string Employees { get; set; }
        public Nullable<double> annualIncome { get; set; }
        public string Comment { get; set; }
        public string Email { get; set; }
        public string phone { get; set; }
        public string sites { get; set; }
        public string Street { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_responsible> company_responsible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact> contacts { get; set; }
    }
}
