//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal()
        {
            this.Customer_Request = new HashSet<Customer_Request>();
            this.Deal_Item = new HashSet<Deal_Item>();
            this.Deal_SaleRep_Respon = new HashSet<Deal_SaleRep_Respon>();
            this.orders = new HashSet<order>();
            this.DealTasks = new HashSet<DealTask>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int Stage { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> Probability { get; set; }
        public string Creator { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CompleteOn { get; set; }
        public int Client { get; set; }
        public Nullable<System.DateTime> LastUpdateStage { get; set; }
        public Nullable<int> Status { get; set; }
        public int ProductID { get; set; }
        public int CurrentPlanID { get; set; }
    
        public virtual contact contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Request> Customer_Request { get; set; }
        public virtual DealStatu DealStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_Item> Deal_Item { get; set; }
        public virtual PrePurchase_FollowUp_Plan PrePurchase_FollowUp_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_SaleRep_Respon> Deal_SaleRep_Respon { get; set; }
        public virtual softwareProduct softwareProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealTask> DealTasks { get; set; }
    }
}
