//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketComment
    {
        public int id { get; set; }
        public string Creator { get; set; }
        public string Description { get; set; }
        public int ticketID { get; set; }
        public bool Accepted { get; set; }
        public int point { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
